name: antoine
favicon: null
layout_spectrum: 0.74444
typography_spectrum: 0.3810509273316711
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#212121'
    - '#f5f5f5'
    - '#cdcdcd'
    - '#6b6b6b'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
