name: antoine
favicon: null
layout_spectrum: 0.74444
typography_spectrum: 0.3810509273316711
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3125
  lightness: 0.9900824637152255
  saturation: 0.27906088763847947
  rhythmicContrast: 0.593196943635121
purpose: []
